// Populated synthetic browser evidence copied from existing regression fixtures.
// This file is test-only: it is not imported by the application or production build.
// Preserve unavailable/null entries; these payloads establish no live-source verification.
import type { JourneyData } from '../../src/features/journey/model/useJourneyModel';
import type { SalesActivationData } from '../../src/lib/offernetClient';
import { DISPOSITION_REPORT_VERSION, type ContactDispositionsData } from '../../contracts/vendorDispositions';

// tests/journey-and-contact-contracts.test.ts: independent totals vs transition intersections.
// The two vendor rows overlap (11 vendor memberships vs 10 distinct fetched leads).
export const convergenceJourneyPayload: JourneyData = {
  velocity: {
    fetchToDelivery: '10s',
    deliveryToFirstDial: '20s',
    firstDialToContact: 'Unavailable',
    contactToSale: '30s',
    saleToActivation: '40s',
  },
  byVendor: [
    { vendor: 'VendorA', leads: 6, delivered: 5, dialled: 4, contacted: 3, sales: 2, activations: 1 },
    { vendor: 'VendorB', leads: 5, delivered: 4, dialled: 3, contacted: 2, sales: 2, activations: 1 },
    // Note: vendor rows sum to 11 leads (overlapping), establishing why summing byVendor rows is invalid!
  ],
  bySource: [],
  byGrade: [],
  lifecycle: {
    period: null,
    comparisons: {
      fetched: { current: 10, previous: null, kind: 'count', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      delivered: { current: 8, previous: null, kind: 'count', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      dialled: { current: 7, previous: null, kind: 'count', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      rpc: { current: 4, previous: null, kind: 'count', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      sales: { current: 3, previous: null, kind: 'count', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      activations: { current: 2, previous: null, kind: 'count', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      deliveryRate: { current: 80.0, previous: null, kind: 'rate', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      dialRate: { current: 87.5, previous: null, kind: 'rate', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      rpcRate: { current: 57.14, previous: null, kind: 'rate', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      saleRate: { current: 30.0, previous: null, kind: 'rate', absoluteChange: null, percentageChange: null, percentagePointChange: null },
      activationRate: { current: 66.67, previous: null, kind: 'rate', absoluteChange: null, percentageChange: null, percentagePointChange: null },
    },
    transitions: [
      { from: 'Capture', to: 'Delivery', population: 10, converted: 8, lost: 2, conversionRate: 80.0, lossRate: 20.0, deteriorationPp: null, status: 'OBSERVED' },
      { from: 'Delivery', to: 'Dial', population: 8, converted: 6, lost: 2, conversionRate: 75.0, lossRate: 25.0, deteriorationPp: null, status: 'NON_NESTED' },
      { from: 'Dial', to: 'RPC', population: 7, converted: 4, lost: 3, conversionRate: 57.14, lossRate: 42.86, deteriorationPp: null, status: 'OBSERVED' },
      { from: 'RPC', to: 'Sale', population: 4, converted: 2, lost: 2, conversionRate: 50.0, lossRate: 50.0, deteriorationPp: null, status: 'NON_NESTED' },
      { from: 'Sale', to: 'Activation', population: 3, converted: 2, lost: 1, conversionRate: 66.67, lossRate: 33.33, deteriorationPp: null, status: 'OBSERVED' },
    ],
    largestLeakage: null,
    largestDeterioration: null,
    segments: {},
    priorSegments: {},
    rateContributions: {},
    velocity: { captureToDeliverySec: 10, deliveryToDialSec: 20, dialToSaleSec: 30, saleToActivationSec: 40 },
    validationStatus: 'NOT_VERIFIED',
    methodology: 'Test',
    unsupportedDimensions: [],
  },
};

// scripts/build-ledger-timeline-fixture.mjs: existing populated contact-effort response.
// Revenue, cost and individual-call sequence evidence remain explicitly unavailable.
export const convergenceContactPayload = {attemptPerformance:[{bucket:'0 calls',leads:20,sharePct:20,contacted:0,contactRate:0,sales:0,saleRate:0,activations:0,activationRate:0,revenue:null,callCost:null,marginalSales:null,marginalCostPerSale:null},{bucket:'1 call',leads:80,sharePct:80,contacted:12,contactRate:15,sales:10,saleRate:12.5,activations:0,activationRate:0,revenue:null,callCost:null,marginalSales:null,marginalCostPerSale:null}],attemptCadence:[],summary:{totalLeads:100,dialledLeads:80,unrecordedCallLeads:0,zeroCallLeads:20,oneCallLeads:80,singleAttemptSharePct:100,multiAttemptLeads:0,multiAttemptSharePct:0,fivePlusCallLeads:0,fivePlusNoRpcLeads:0},methodology:'Synthetic returned effort evidence; missing is not zero.',noAnswerAnalysis:{status:'UNAVAILABLE',reason:'Individual synthetic call times are not supplied',stopThresholdRecommendation:null,diminishingReturnsCutoff:null,callbackFollowupRate:null,callbackSaleConversion:null}};

// tests/sales-activation-contracts.test.ts: independent outcomes and all ageing buckets.
// The unactivated population is the returned 35, not total sales minus activations.
export const convergenceSalesPayload: SalesActivationData = {
  reconciliation: {
    totalSales: 100,
    billableSales: 80,
    salesWithRecordedRevenue: 85,
    unbilledSales: 15,
    unrecordedRevenueSales: 0,
    totalActivations: 70,
    activationRate: 70.0,
    realizedRevenue: 150000,
    avgTimeToSale: '2.5h',
    avgTimeToActivation: '3.2d',
    medianTimeToSale: '1.2h',
    medianTimeToActivation: '2.0d',
  },
  maturationCurve: [],
  maturationStatus: 'UNAVAILABLE',
  maturationReason: 'Activation maturation is withheld until event-level activation joins are independently validated.',
  byVendor: [
    { vendor: 'Partner A', sales: 60, activations: 45, revenue: 90000, unrecorded_revenue_sales: 0 },
    { vendor: 'Partner B', sales: 40, activations: 25, revenue: 60000, unrecorded_revenue_sales: 0 },
  ],
  bySource: [
    { dimension: 'source', segment: 'Google PPC', sales: 70, activations: 50, revenue: 105000, unrecorded_revenue_sales: 0 },
    { dimension: 'source', segment: 'Facebook', sales: 30, activations: 20, revenue: 45000, unrecorded_revenue_sales: 0 },
  ],
  byGrade: [
    { dimension: 'grade', segment: 'Tier 1', sales: 80, activations: 60, revenue: 120000, unrecorded_revenue_sales: 0 },
    { dimension: 'grade', segment: 'Tier 2', sales: 20, activations: 10, revenue: 30000, unrecorded_revenue_sales: 0 },
  ],
  activationAgeing: [
    { bucket: '0–3d', sales: 12 },
    { bucket: '4–7d', sales: 8 },
    { bucket: '8–14d', sales: 6 },
    { bucket: '15–30d', sales: 4 },
    { bucket: '30d+', sales: 3 },
    { bucket: 'Invalid future sale', sales: 2 },
  ],
  revenueEvidence: 'Recorded revenue is the sum of available source values.',
  segmentMethodology: 'One lead per segment.',
};

// tests/journey-and-contact-contracts.test.ts: raw disposition and mapping-state fixture.
// Only clientId is adapted to the authorised synthetic browser workspace below.
const dispositionFixture: ContactDispositionsData = {
  reportVersion: DISPOSITION_REPORT_VERSION,
  mode: 'lead_status',
  modeHeading: 'Current recorded status for the selected capture cohort',
  modeDescription: 'Reconciles repeated HLC records deterministically per lead-vendor pair.',
  dateBasis: 'lead_capture_cohort',
  countingGrain: 'lead_vendor_pairs',
  clientId: 'tenant-omega',
  timezone: 'Africa/Johannesburg',
  summary: {
    totalEntities: 500,
    dialledEntities: 400,
    zeroCallEntities: 60,
    unrecordedActivityEntities: 40,
    conflictingEntities: 20,
    recordedDispositions: 350,
    missingDispositions: 50,
    unmappedDispositions: 30,
    dispositionCoveragePct: 87.5,
    mappingCoveragePct: 91.4,
    rpcCount: 150,
    saleCount: 50,
    callbackCount: 30,
  },
  vendorSummaries: [
    {
      vendor: 'CallForce',
      totalPopulation: 300,
      dialledCount: 250,
      recordedDispositionCount: 220,
      missingDispositionCount: 30,
      unmappedDispositionCount: 20,
      dispositionCoveragePct: 88.0,
      mappingCoveragePct: 90.9,
      rpcCount: 100,
      saleCount: 35,
      callbackCount: 20,
      sourceTable: 'clustered_lead_ledger.hlc_details',
      dateBasis: 'lead_capture_cohort',
      latestObservedFeedback: null,
      coverageLimitations: [],
    },
    {
      vendor: 'Mondo',
      totalPopulation: 200,
      dialledCount: 150,
      recordedDispositionCount: 130,
      missingDispositionCount: 20,
      unmappedDispositionCount: 10,
      dispositionCoveragePct: 86.7,
      mappingCoveragePct: 92.3,
      rpcCount: 50,
      saleCount: 15,
      callbackCount: 10,
      sourceTable: 'clustered_lead_ledger.hlc_details',
      dateBasis: 'lead_capture_cohort',
      latestObservedFeedback: null,
      coverageLimitations: [],
    },
  ],
  breakdown: [
    {
      vendor: 'CallForce',
      rawDisposition: 'RPC_HUMAN',
      rawDescription: 'Right Party Contact Human',
      approvedGroup: 'CONTACTED_RPC',
      approvedGroupLabel: 'Contacted / RPC',
      count: 60,
      percentOfBase: 24.0,
      distinctLeadVendorPairs: 60,
      rpcCount: 60,
      saleCount: 0,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      mappingStatus: 'APPROVED',
    },
    {
      vendor: 'CallForce',
      rawDisposition: 'RPC_CALLBACK',
      rawDescription: 'Customer Requested Callback',
      approvedGroup: 'CONTACTED_RPC',
      approvedGroupLabel: 'Contacted / RPC',
      count: 40,
      percentOfBase: 16.0,
      distinctLeadVendorPairs: 40,
      rpcCount: 40,
      saleCount: 0,
      callbackCount: 20,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      mappingStatus: 'APPROVED',
    },
    {
      vendor: 'CallForce',
      rawDisposition: 'SALE_MADE',
      rawDescription: 'Sale Closed Deal',
      approvedGroup: 'REPORTED_SALE',
      approvedGroupLabel: 'Reported Sale',
      count: 35,
      percentOfBase: 14.0,
      distinctLeadVendorPairs: 35,
      rpcCount: 35,
      saleCount: 35,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      mappingStatus: 'APPROVED',
    },
    {
      vendor: 'CallForce',
      rawDisposition: 'UNMAPPED_RAW_X',
      rawDescription: 'Unknown code from CallForce',
      approvedGroup: 'UNMAPPED',
      approvedGroupLabel: 'Unmapped Disposition',
      count: 20,
      percentOfBase: 8.0,
      distinctLeadVendorPairs: 20,
      rpcCount: 0,
      saleCount: 0,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      isUnmapped: true,
      mappingStatus: 'UNMAPPED',
    },
    {
      vendor: 'CallForce',
      rawDisposition: 'MISSING_DISPOSITION',
      rawDescription: 'Missing disposition code',
      approvedGroup: 'MISSING_DISPOSITION',
      approvedGroupLabel: 'Missing Disposition',
      count: 30,
      percentOfBase: 12.0,
      distinctLeadVendorPairs: 30,
      rpcCount: 0,
      saleCount: 0,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      mappingStatus: 'MISSING',
    },
    {
      vendor: 'CallForce',
      rawDisposition: 'CONFLICTING_EVIDENCE',
      rawDescription: 'Contradictory status observations',
      approvedGroup: 'CONFLICTING_EVIDENCE',
      approvedGroupLabel: 'Conflicting Evidence',
      count: 20,
      percentOfBase: 8.0,
      distinctLeadVendorPairs: 20,
      rpcCount: 5,
      saleCount: 0,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      mappingStatus: 'CONFLICTING',
    },
    {
      vendor: 'CallForce',
      rawDisposition: 'UNKNOWN_CUSTOM_CODE',
      rawDescription: 'Unclassified operational code',
      approvedGroup: 'OTHER',
      approvedGroupLabel: 'Other',
      count: 10,
      percentOfBase: 4.0,
      distinctLeadVendorPairs: 10,
      rpcCount: 0,
      saleCount: 0,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      mappingStatus: undefined, // Absent status
    },
    {
      vendor: 'CallForce',
      rawDisposition: 'CONTRADICTORY_CODE',
      rawDescription: 'Marked approved but flagged unmapped',
      approvedGroup: 'OTHER',
      approvedGroupLabel: 'Other',
      count: 5,
      percentOfBase: 2.0,
      distinctLeadVendorPairs: 5,
      rpcCount: 0,
      saleCount: 0,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      isUnmapped: true,
      mappingStatus: 'APPROVED', // Contradictory fields!
    },
    {
      vendor: 'Mondo',
      rawDisposition: 'SALE',
      rawDescription: 'Approved Deal',
      approvedGroup: 'REPORTED_SALE',
      approvedGroupLabel: 'Reported Sale',
      count: 15,
      percentOfBase: 10.0,
      distinctLeadVendorPairs: 15,
      rpcCount: 15,
      saleCount: 15,
      callbackCount: 0,
      avgDurationSec: null,
      validDurationCount: null,
      latestObservation: null,
      mappingStatus: 'APPROVED',
    },
  ],
  matrix: [],
  trends: [],
  comparableGroups: [],
  capabilities: {
    leadStatusSupported: true,
    callRecordsSupported: true,
    supportedFilters: [],
    unsupportedFilters: [],
  },
  methodology: 'Test',
  evaluatedAt: '2026-09-27T10:00:00.000Z',
};
export const convergenceDispositionPayload: ContactDispositionsData = {
  ...dispositionFixture,
  clientId: 'synthetic-a',
};

export const convergencePayloads = {
  '/api/analytics/offernet/funnel': convergenceJourneyPayload,
  '/api/analytics/offernet/contact-strategy': convergenceContactPayload,
  '/api/analytics/offernet/contact-dispositions': convergenceDispositionPayload,
  '/api/analytics/offernet/sales-activation': convergenceSalesPayload,
};
