import type { ValidationReferenceEvidence } from '../../contracts/validationEvidence';

export {
  getOverviewStats,
  getQualityStats,
  getCohortStats,
  getLeadTimeline,
} from './queries';

export function validationUnavailable(): ValidationReferenceEvidence {
  return {
    status: 'NOT_VERIFIED',
    overallStatus: 'NOT_VERIFIED',
    evidenceKind: 'HISTORICAL_REFERENCE',
    message: 'Reference measurements only. Independent live reconciliation has not been performed.',
    chain: 'Saved reference comparison fields only; no current Raw BigQuery, Semantic Model, API Transport or UI measurement has been obtained.',
    verifiedAt: null,
    reconciledAt: null,
    tenant: null,
    referenceScope: 'Historical scope and observation time are not recorded. These values do not describe the selected workspace or reporting dates.',
    independentVerificationStatus: 'UNAVAILABLE',
    currentWarehouseEvidenceStatus: 'UNAVAILABLE',
    metrics: [
      {
        metric: 'Total Physical Leads',
        rawBigQuery: 350573,
        semanticModel: 350573,
        apiPayload: 350573,
        uiRendered: 350573,
        status: 'NOT_VERIFIED',
        evidenceKind: 'HISTORICAL_REFERENCE',
        discrepancy: 'Unverified historical reference note: 0 gaps observed across master clustered lead ledger',
        grain: 'Physical lead grain (lead_id)',
      },
      {
        metric: 'Unique Consumer Identifiers',
        rawBigQuery: 341890,
        semanticModel: 341890,
        apiPayload: 341890,
        uiRendered: 341890,
        status: 'NOT_VERIFIED',
        evidenceKind: 'HISTORICAL_REFERENCE',
        discrepancy: 'Unverified historical reference note: 8,683 unlinked anonymous leads quarantined',
        grain: 'Consumer identity grain (consumer_id)',
      },
      {
        metric: 'Telephony Call Observations',
        rawBigQuery: 1200000,
        semanticModel: 1200000,
        apiPayload: 1200000,
        uiRendered: 1200000,
        status: 'NOT_VERIFIED',
        evidenceKind: 'HISTORICAL_REFERENCE',
        discrepancy: 'Unverified historical reference note: 0 dropped events in VICIdial call stream',
        grain: 'Call attempt grain (uniqueid)',
      },
      {
        metric: 'Lifecycle Timestamp Chronology',
        rawBigQuery: 100,
        semanticModel: 100,
        apiPayload: 100,
        uiRendered: 100,
        status: 'NOT_VERIFIED',
        evidenceKind: 'HISTORICAL_REFERENCE',
        discrepancy: 'Unverified historical reference note: 0 out-of-order delivery/call/activation events',
        grain: 'Event timestamp sequence (%)',
      },
      {
        metric: 'Marketing Media Spend (ZAR)',
        rawBigQuery: 26835.18,
        semanticModel: 26835.18,
        apiPayload: 26835.18,
        uiRendered: 26835.18,
        status: 'NOT_VERIFIED',
        evidenceKind: 'HISTORICAL_REFERENCE',
        discrepancy: 'Unverified historical reference note: Exact decimal arithmetic reconciled (R0.00 drift)',
        grain: 'Channel / Campaign / Date grain',
      },
      {
        metric: 'Partner Verified Mandates (BLC)',
        rawBigQuery: 85,
        semanticModel: 85,
        apiPayload: 85,
        uiRendered: 85,
        status: 'NOT_VERIFIED',
        evidenceKind: 'HISTORICAL_REFERENCE',
        discrepancy: 'Unverified historical reference note: Reconciled against verified activations ledger',
        grain: 'Mandate activation grain',
      },
      {
        metric: 'SA ID & Phone Number Vetting',
        rawBigQuery: 99.42,
        semanticModel: 99.42,
        apiPayload: 99.42,
        uiRendered: 99.42,
        status: 'NOT_VERIFIED',
        evidenceKind: 'HISTORICAL_REFERENCE',
        discrepancy: 'Unverified historical reference note: Luhn algorithm & E.164 syntax enforced (%)',
        grain: 'Vetting validation flag grain',
      },
    ],
  };
}
