import React from 'react';
import { exactAuditDelta, formatAuditValue, RECONCILIATION_KIND_LABELS, type AuditReconciliationModel } from './auditVisualModel';
import { AuditStateLabel } from './EvidenceTrace';
export type { AuditReconciliationModel, AuditComparison } from './auditVisualModel';

export default function ReconciliationView({ model }: { model: AuditReconciliationModel }) {
  const deltas = model.comparisons?.map(comparison => exactAuditDelta(comparison.observed, comparison.expected)) || [];
  const coordinates = deltas.map(delta => delta === null ? null : Number(delta));
  const maximum = Math.max(0, ...coordinates.map(value => value !== null && Number.isFinite(value) ? Math.abs(value) : 0));
  return <section className="cx-audit-reconciliation" aria-label={model.label} data-reconciliation-kind={model.kind}><h3>{model.label}</h3><p className="cx-audit-reconciliation-kind">{RECONCILIATION_KIND_LABELS[model.kind]}</p><AuditStateLabel state={model.state}/>{model.scopeDescription && <p>Comparison scope: {model.scopeDescription}</p>}
    {model.values.length > 0 && <ul className="cx-audit-population-list">{model.values.map(population => <li key={population.key}><span>{population.label}</span><strong className="cx-audit-exact-value">{formatAuditValue(population.value)}</strong>{population.state && <AuditStateLabel state={population.state}/>} {population.detail && <p>{population.detail}</p>}</li>)}</ul>}
    {model.comparisons?.length ? <div className="cx-audit-comparison-scroll" role="region" tabIndex={0} aria-label="Exact comparison values"><table className="cx-audit-comparison-table"><caption>Signed difference = observed minus expected</caption><thead><tr><th scope="col">Comparison</th><th scope="col">Expected</th><th scope="col">Observed</th><th scope="col">Exact difference</th></tr></thead><tbody>{model.comparisons.map((comparison, index) => <tr key={comparison.key}><th scope="row">{comparison.label}{comparison.detail && <small>{comparison.detail}</small>}</th><td>{formatAuditValue(comparison.expected)}</td><td>{formatAuditValue(comparison.observed)}</td><td><strong>{deltas[index] ?? 'Unavailable'}</strong><div className="cx-audit-delta-track" aria-hidden="true"><span className="cx-audit-delta-axis"/>{coordinates[index] !== null && Number.isFinite(coordinates[index]) && <span className="cx-audit-delta-bar" data-direction={coordinates[index]! < 0 ? 'negative' : coordinates[index]! > 0 ? 'positive' : 'zero'} style={{ width: `${maximum > 0 ? Math.abs(coordinates[index]!) / maximum * 50 : 0}%` }}/>}</div></td></tr>)}</tbody></table></div> : null}
    <p className="cx-audit-visual-note">{model.kind === 'delivery_consistency' ? 'Agreement between pipeline values checks delivery consistency. It does not establish independent source reconciliation or business approval.' : model.kind === 'formula_check' ? 'Arithmetic agreement checks the supplied formula. It does not establish source reconciliation or business approval.' : model.kind === 'source_reconciliation' ? 'The shown status is supplied evidence for this comparison scope. A zero difference does not create a verification status.' : 'Business verification requires an explicit approval of source meaning. Numeric agreement alone does not establish it.'}</p>{model.detail && <p>{model.detail}</p>}
  </section>;
}
