import { compareMetric } from '../../contracts/periodComparison';
import { useState } from 'react';
import type { LifecycleDiagnostics, LifecycleSegment } from '../../contracts/lifecycleAnalytics';
import { formatPercent, formatTableCurrency, formatTableNumber } from '../lib/formatters';
import ExportAnalysisButton from './ExportAnalysisButton';

const signed = (value: number | null | undefined, suffix = '') => value == null ? '—' : `${value > 0 ? '+' : ''}${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}${suffix}`;
const names: Record<string,string> = { fetched:'Fetched', delivered:'Delivered', dialled:'Dialled', rpc:'RPC', sales:'Sales', activations:'Activations', revenue:'Recorded revenue', deliveryRate:'Delivery rate', dialRate:'Dial coverage', rpcRate:'RPC / dialled', saleRate:'Lead → sale', activationRate:'Sale → activation' };
export function MatchedPeriodPanel({ data }: { data: LifecycleDiagnostics }) {
  return <section className="cx-command-panel"><header><div><span className="cx-command-section-kicker">Change</span><h2>Matched period comparison</h2><p>{data.period ? `${data.period.current.startDate}–${data.period.current.endDate} vs ${data.period.previous.startDate}–${data.period.previous.endDate} · ${data.period.days} calendar days each` : 'Choose an inclusive date range of up to 366 days to compare the immediately preceding equal-length period.'}</p></div></header>
    {data.period && <div className="cx-performance-table-wrap"><table className="cx-performance-table"><thead><tr><th>Metric</th><th>Current</th><th>Previous</th><th>Change</th><th>Relative change</th></tr></thead><tbody>{Object.entries(data.comparisons).map(([key, row]) => <tr key={key}><th>{names[key] || key}</th><td>{row.kind === 'rate' ? formatPercent(row.current, 2) : formatTableNumber(row.current)}</td><td>{row.kind === 'rate' ? formatPercent(row.previous, 2) : formatTableNumber(row.previous)}</td><td>{signed(row.kind === 'rate' ? row.percentagePointChange : row.absoluteChange, row.kind === 'rate' ? 'pp' : '')}</td><td>{signed(row.percentageChange, '%')}</td></tr>)}</tbody></table></div>}
    <p className="cx-control-note">Capture cohorts have different follow-up maturity. Changes are measured associations; validation remains {data.validationStatus}.</p>
  </section>;
}
export function LifecycleFunnelPanel({ data }: { data: LifecycleDiagnostics }) {
  return <section className="cx-command-panel"><header><div><span className="cx-command-section-kicker">Lifecycle loss</span><h2>Where leads stop</h2><p>{data.largestLeakage ? `Largest loss: ${data.largestLeakage.from} → ${data.largestLeakage.to}, ${formatTableNumber(data.largestLeakage.lost)} leads.` : 'No measured transition loss in this scope.'} {data.largestDeterioration ? `Largest deterioration: ${data.largestDeterioration.from} → ${data.largestDeterioration.to}, ${signed(data.largestDeterioration.deteriorationPp, 'pp')}.` : ''}</p></div></header>
  <div className="cx-performance-table-wrap"><table className="cx-performance-table"><thead><tr><th>Transition</th><th>Population</th><th>With both events</th><th>Conversion</th><th>Lost</th><th>Loss</th><th>Prior change</th><th>Evidence</th></tr></thead><tbody>{data.transitions.map(r => <tr key={r.from}><th>{r.from} → {r.to}</th><td>{formatTableNumber(r.population)}</td><td>{formatTableNumber(r.converted)}</td><td>{formatPercent(r.conversionRate)}</td><td>{formatTableNumber(r.lost)}</td><td>{formatPercent(r.lossRate)}</td><td>{signed(r.deteriorationPp, 'pp')}</td><td>{r.status === 'NON_NESTED' ? 'Downstream events also exist without this prior stage' : 'Observed'}</td></tr>)}</tbody></table></div></section>;
}
export function LifecycleSegmentsPanel({ data, initialDimension = 'vendor' }: { data: LifecycleDiagnostics; initialDimension?: string }) {
  const [dimension, setDimension] = useState(initialDimension);
  const [comparisonMetric, setComparisonMetric] = useState<'fetched'|'delivered'|'dialled'|'rpc'|'sales'|'activations'|'deliveryRate'|'dialRate'|'rpcRate'|'saleRate'|'activationRate'>('saleRate');
  const [sort, setSort] = useState<'fetched'|'saleRate'|'activationRate'|'rpcRate'>('fetched');
  const rows = [...(data.segments[dimension] || [])].sort((a,b) => (b[sort] ?? -1) - (a[sort] ?? -1));
  const previous = new Map((data.priorSegments[dimension] || []).map(r => [r.key, r]));
  const contribution = data.rateContributions?.[comparisonMetric]?.[dimension] || (comparisonMetric === 'saleRate' ? data.contributions[dimension] : null);
  const current = new Map(rows.map(r => [r.key,r]));
  const comparisonRows = [...new Set([...current.keys(),...previous.keys()])].map(key => {
    const kind = comparisonMetric.endsWith('Rate') ? 'rate' : 'count';
    return {key,...compareMetric(current.get(key)?.[comparisonMetric] ?? (kind === 'count' ? 0 : null), previous.get(key)?.[comparisonMetric] ?? (kind === 'count' ? 0 : null),kind)};
  });
  const exportRows = [['Segment','Fetched','Delivered','Dialled','RPC','Sales','Activations','Delivery %','Dial %','RPC %','Lead → sale %','Sale → activation %','15m SLA %','One-call share %','5+ no RPC','Disposition completeness %','Recorded revenue subtotal','Leads without recorded revenue'], ...rows.map(r => [r.key,r.fetched,r.delivered,r.dialled,r.rpc,r.sales,r.activations,r.deliveryRate,r.dialRate,r.rpcRate,r.saleRate,r.activationRate,r.within15mRate,r.oneCallShare,r.fivePlusNoRpc,r.dispositionCompleteness,r.revenue,r.missingRevenueLeads])];
  return <section className="cx-command-panel"><header><div><span className="cx-command-section-kicker">Segments</span><h2>Lifecycle and change by {dimension}</h2><p>Compare explicit metrics. Vendor figures here use one assigned vendor per lead so the totals reconcile.</p></div><ExportAnalysisButton rows={exportRows} filename={`lifecycle_${dimension}`} definitions={[data.methodology]} /></header>
  <div className="cx-control-note"><label>Dimension <select aria-label="Lifecycle dimension" value={dimension} onChange={e => setDimension(e.target.value)}>{Object.keys(data.segments).map(d => <option key={d} value={d}>{d}</option>)}</select></label> <label>Sort by <select aria-label="Sort lifecycle segments" value={sort} onChange={e => setSort(e.target.value as typeof sort)}><option value="fetched">Fetched</option><option value="saleRate">Lead → sale</option><option value="rpcRate">RPC / dialled</option><option value="activationRate">Sale → activation</option></select></label></div>
  <div className="cx-performance-table-wrap"><table className="cx-performance-table"><thead><tr><th>Segment</th><th>Fetched</th><th>Delivered</th><th>Dialled</th><th>RPC</th><th>Sales</th><th>Activations</th><th>Delivery %</th><th>Dial %</th><th>RPC %</th><th>Lead → sale %</th><th>Prior sale %</th><th>Δ pp</th><th>Activation %</th><th>15m / delivered</th><th>One call / dialled</th><th>5+ no RPC</th><th>Disposition</th><th>Invalid leads</th><th>Missing source</th><th>Missing grade</th><th>Recorded revenue subtotal</th><th>Leads without recorded revenue</th></tr></thead><tbody>{rows.map(r => { const prior = previous.get(r.key); return <tr key={r.key}><th>{r.key}</th>{(['fetched','delivered','dialled','rpc','sales','activations'] as const).map(k => <td key={k}>{formatTableNumber(r[k])}</td>)}{(['deliveryRate','dialRate','rpcRate','saleRate'] as const).map(k => <td key={k}>{formatPercent(r[k],2)}</td>)}<td>{formatPercent(prior?.saleRate,2)}</td><td>{signed(r.saleRate != null && prior?.saleRate != null ? r.saleRate-prior.saleRate : null, 'pp')}</td><td>{formatPercent(r.activationRate)}</td><td>{formatPercent(r.within15mRate)}</td><td>{formatPercent(r.oneCallShare)}</td><td>{formatTableNumber(r.fivePlusNoRpc)}</td><td>{formatPercent(r.dispositionCompleteness)}</td><td>{formatTableNumber(r.invalidLeads)}</td><td>{formatTableNumber(r.missingSource)}</td><td>{formatTableNumber(r.missingGrade)}</td><td>{formatTableCurrency(r.revenue, 'R')}</td><td>{formatTableNumber(r.missingRevenueLeads)}</td></tr>;})}</tbody></table></div>
  {data.period && <><header><div><h2>Segment comparison</h2><p>{data.period.days} matched days. Entering and exiting segments are included.</p></div><label>Compare <select aria-label="Segment comparison metric" value={comparisonMetric} onChange={e=>setComparisonMetric(e.target.value as typeof comparisonMetric)}>{['fetched','delivered','dialled','rpc','sales','activations','deliveryRate','dialRate','rpcRate','saleRate','activationRate'].map(k=><option value={k} key={k}>{names[k]}</option>)}</select></label></header><div className="cx-performance-table-wrap"><table className="cx-performance-table"><thead><tr><th>Segment</th><th>Current {names[comparisonMetric]}</th><th>Previous</th><th>Absolute / pp change</th><th>Relative change</th></tr></thead><tbody>{comparisonRows.map(r=><tr key={r.key}><th>{r.key}</th><td>{r.kind==='rate'?formatPercent(r.current,2):formatTableNumber(r.current)}</td><td>{r.kind==='rate'?formatPercent(r.previous,2):formatTableNumber(r.previous)}</td><td>{signed(r.kind==='rate'?r.percentagePointChange:r.absoluteChange,r.kind==='rate'?'pp':'')}</td><td>{signed(r.percentageChange,'%')}</td></tr>)}</tbody></table></div></>}
  {contribution && <><header><div><h2>Contribution to overall {names[comparisonMetric]} change</h2><p>{signed(contribution.deltaPp,'pp')} total · {contribution.status}. Contributions below sum to this change. Each dimension is a separate decomposition.</p></div></header><div className="cx-performance-table-wrap"><table className="cx-performance-table"><thead><tr><th>Segment</th><th>Current outcome count</th><th>Previous outcome count</th><th>Contribution</th></tr></thead><tbody>{contribution.contributions.map(c => <tr key={c.key}><th>{c.key}</th><td>{formatTableNumber(c.currentNumerator)}</td><td>{formatTableNumber(c.previousNumerator)}</td><td>{signed(c.contributionPp,'pp')}</td></tr>)}</tbody></table></div><p className="cx-control-note">{contribution.method}</p></>}
  <p className="cx-control-note">{data.methodology} Revenue is the sum of available recorded lead values; missing values are not imputed. The missing-revenue column counts leads without any recorded revenue, not all incomplete nested source values. Campaign and channel segmentation are unavailable until an approved operational mapping exists.</p></section>;
}
