/**
 * Authoritative Server-Owned Capability and Metric Registry Contract
 * Version: cx.metric.3.0.0
 * 
 * Enforces strict mathematical rules, explicit non-ambiguous labels, counting grains,
 * date bases, precision, and handling of missing/unknown outcomes.
 */

export const METRIC_REGISTRY_VERSION = 'cx.metric.3.0.0';

export type CountingGrain =
  | 'lead'
  | 'lead_vendor_route'
  | 'vendor_transaction_row'
  | 'call_event'
  | 'contract'
  | 'source_aggregate';

export type DateBasis =
  | 'intake_cohort'
  | 'activity_period'
  | 'fixed_age_horizon';

export type MetricUnit =
  | 'records'
  | 'percent'
  | 'currency'
  | 'seconds'
  | 'calls_per_lead';

export type UnknownTreatment =
  | 'excluded_from_numerator_and_denominator'
  | 'withheld_if_unverified'
  | 'explicit_false_only'
  | 'preserved_in_missing_discrepancy'
  | 'zero_not_assumed';

export interface AuthoritativeMetricDefinition {
  id: string;
  businessLabel: string;
  technicalLabel: string;
  plainDefinition: string;
  version: typeof METRIC_REGISTRY_VERSION;
  countingGrain: CountingGrain;
  distinctIdentity: 'consumer' | 'submission' | 'lead' | 'lead_vendor_route' | 'delivery' | 'call_event' | 'sale' | 'contract';
  source: string;
  fields: string[];
  precedence: string;
  relationshipKey: string;
  unit: MetricUnit;
  currency?: string;
  numerator: string;
  numeratorDescription: string;
  denominator: string | null;
  denominatorDescription: string | null;
  eligibility: string;
  exclusions: string;
  scaling: 'percentage_value' | 'ratio_fraction' | 'none';
  dateBasis: DateBasis;
  timezone: string;
  observationCutoff: string;
  additive: boolean;
  treatmentOfUnknown: UnknownTreatment;
  supportedClients: string[];
  supportedDimensions: string[];
  supportedComparisons: string[];
  detailPermissions: 'viewer' | 'analyst' | 'admin';
  /** Mapping approval is implementation metadata, not business certification or live reconciliation. */
  mappingStatus: 'APPROVED' | 'PROVISIONAL' | 'UNRESOLVED';
  sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED';
  reconciliationStatus: 'RECONCILED' | 'PARTIAL' | 'NOT_VERIFIED' | 'UNAVAILABLE';
  dependencies: string[];
  caveats: string[];
}

export const AUTHORITATIVE_METRICS: Record<string, AuthoritativeMetricDefinition> = {
  fetched_leads: {
    id: 'fetched_leads',
    businessLabel: 'Fetched leads',
    technicalLabel: 'Fetched cohort leads',
    plainDefinition: 'Total count of unique leads captured and ingested into OfferNet during the selected intake period.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads',
    fields: ['lead_id', 'fetched'],
    precedence: 'Earliest observed fetch timestamp MIN(fetched)',
    relationshipKey: 'lead_id',
    unit: 'records',
    numerator: 'COUNT(DISTINCT lead_id)',
    numeratorDescription: 'Distinct lead identifiers fetched within the reporting window.',
    denominator: null,
    denominatorDescription: null,
    eligibility: 'All distinct leads with valid fetch timestamp within scope dates.',
    exclusions: 'Duplicate submissions under the same distinct lead identifier are collapsed.',
    scaling: 'none',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Latest partition timestamp in BigQuery source table',
    additive: true,
    treatmentOfUnknown: 'preserved_in_missing_discrepancy',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade', 'medium', 'client'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'admin',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads'],
    caveats: ['Distinct lead grain; duplicate submissions collapsed under documented identity rules.'],
  },

  attempted_delivery_leads: {
    id: 'attempted_delivery_leads',
    businessLabel: 'Attempted delivery',
    technicalLabel: 'Leads with attempted delivery timestamp',
    plainDefinition: 'Distinct leads where a delivery event was dispatched to an operational or vendor queue.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['lead_id', 'hlc.attempted_to_deliver'],
    precedence: 'Earliest observed attempted delivery timestamp MIN(attempted_to_deliver)',
    relationshipKey: 'lead_id',
    unit: 'records',
    numerator: 'COUNT(DISTINCT IF(attempted_ts IS NOT NULL, lead_id, NULL))',
    numeratorDescription: 'Distinct leads with a recorded delivery attempt.',
    denominator: null,
    denominatorDescription: null,
    eligibility: 'Distinct leads with valid attempted delivery timestamp.',
    exclusions: 'Unattempted leads; invalid timestamp formats.',
    scaling: 'none',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Latest recorded delivery attempt event',
    additive: true,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'admin',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'deliveries'],
    caveats: ['A delivery attempt is not a confirmed delivery.'],
  },

  delivered_leads: {
    id: 'delivered_leads',
    businessLabel: 'Delivered leads',
    technicalLabel: 'Chronologically qualified delivered leads',
    plainDefinition: 'Distinct intake-cohort leads with a valid recorded delivery timestamp at or after capture.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['lead_id', 'fetched', 'hlc.delivered'],
    precedence: 'Earliest confirmed delivery timestamp MIN(delivered)',
    relationshipKey: 'lead_id',
    unit: 'records',
    numerator: 'COUNT(DISTINCT IF(is_delivered, lead_id, NULL))',
    numeratorDescription: 'Distinct leads with recorded delivery at or after capture.',
    denominator: null,
    denominatorDescription: null,
    eligibility: 'Valid fetched and delivery timestamps, with delivered >= fetched.',
    exclusions: 'Missing predecessor or delivery evidence and delivery before capture are excluded from qualification; recorded evidence remains available.',
    scaling: 'none',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Latest confirmed delivery event timestamp',
    additive: true,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'admin',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'deliveries'],
    caveats: ['Requires valid chronological delivery evidence. Blank, malformed, 1900 and 1970 values are unavailable. Attempted delivery is separate.'],
  },

  delivery_rate: {
    id: 'delivery_rate',
    businessLabel: 'Delivered / fetched',
    technicalLabel: 'Delivery rate (Delivered / fetched)',
    plainDefinition: 'Percentage of fetched leads that reached confirmed delivery in an operational queue.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads',
    fields: ['lead_id', 'fetched', 'hlc.delivered'],
    precedence: 'Delivered distinct leads divided by fetched distinct leads',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'delivered_leads',
    numeratorDescription: 'Distinct delivered leads',
    denominator: 'fetched_leads',
    denominatorDescription: 'Distinct fetched leads',
    eligibility: 'Fetched leads with observed delivery event.',
    exclusions: 'Zero-fetched scope returns unavailable (null), not 0%.',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff',
    additive: false,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads'],
    caveats: ['Rate without a denominator is unavailable, not measured 0%.'],
  },

  dialled_leads: {
    id: 'dialled_leads',
    businessLabel: 'Dialled leads',
    technicalLabel: 'Chronologically qualified dialled leads',
    plainDefinition: 'Distinct intake-cohort leads with valid delivery at or after capture and a recorded first dial at or after both capture and delivery.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['lead_id', 'fetched', 'hlc.delivered', 'hlc.first_call_date'],
    precedence: 'Earliest confirmed call timestamp MIN(first_call_date)',
    relationshipKey: 'lead_id',
    unit: 'records',
    numerator: 'COUNT(DISTINCT IF(is_dialled, lead_id, NULL))',
    numeratorDescription: 'Distinct qualified delivered leads with a chronologically consistent first-dial timestamp.',
    denominator: null,
    denominatorDescription: null,
    eligibility: 'delivered >= fetched and first_call_date >= delivered and first_call_date >= fetched; all three timestamps must be available.',
    exclusions: 'Counters alone, missing predecessors and out-of-order first dials do not qualify. Source-recorded first dials remain separate evidence.',
    scaling: 'none',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Latest verified dial event timestamp',
    additive: true,
    treatmentOfUnknown: 'preserved_in_missing_discrepancy',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'admin',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'calls'],
    caveats: ['Headline dial coverage uses qualified lifecycle progression. Source-recorded first dial remains available even when chronology is invalid.'],
  },

  dial_rate: {
    id: 'dial_rate',
    businessLabel: 'Dialled / delivered',
    technicalLabel: 'Dial rate (Dialled / delivered)',
    plainDefinition: 'Percentage of confirmed delivered leads that received at least one timestamped call attempt.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['fetched', 'hlc.delivered', 'hlc.first_call_date'],
    precedence: 'Dialled distinct leads divided by confirmed delivered distinct leads',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'dialled_leads',
    numeratorDescription: 'Dialled leads',
    denominator: 'delivered_leads',
    denominatorDescription: 'Delivered leads',
    eligibility: 'Delivered leads with timestamp-confirmed dial.',
    exclusions: 'Delivered denominator of 0 returns null (unavailable). Never conflated with Dialled / fetched.',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff',
    additive: false,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'calls'],
    caveats: ['Explicit label: Dialled / delivered. Never conflated with Dialled / fetched.'],
  },

  rpc_leads: {
    id: 'rpc_leads',
    businessLabel: 'Right-party contacts (RPC)',
    technicalLabel: 'RPC leads',
    plainDefinition: 'Distinct chronologically qualified dialled leads with positive source-recorded RPC evidence.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['lead_id', 'fetched', 'hlc.delivered', 'hlc.first_call_date', 'hlc.rpc'],
    precedence: 'Qualified dial plus explicit positive RPC flag; is_qualified_rpc = true',
    relationshipKey: 'lead_id',
    unit: 'records',
    numerator: 'COUNT(DISTINCT IF(is_qualified_rpc, lead_id, NULL))',
    numeratorDescription: 'Distinct qualified dialled leads with positive source-recorded RPC.',
    denominator: null,
    denominatorDescription: null,
    eligibility: 'Dialled leads with recorded positive RPC evidence.',
    exclusions: 'Telephony answers, voicemail, gatekeepers, and missing/null dispositions are not RPC.',
    scaling: 'none',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Latest verified RPC event',
    additive: true,
    treatmentOfUnknown: 'explicit_false_only',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'admin',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'calls'],
    caveats: ['Unknown RPC is null; explicit false is no-RPC. Never treat unknown as negative.'],
  },

  rpc_rate: {
    id: 'rpc_rate',
    businessLabel: 'RPC / dialled',
    technicalLabel: 'RPC rate (RPC / dialled)',
    plainDefinition: 'Percentage of dialled leads that resulted in verified right-party contact.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['fetched', 'hlc.delivered', 'hlc.first_call_date', 'hlc.rpc'],
    precedence: 'RPC leads divided by dialled leads',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'rpc_leads',
    numeratorDescription: 'RPC leads',
    denominator: 'dialled_leads',
    denominatorDescription: 'Dialled leads',
    eligibility: 'Timestamp-confirmed dialled leads with verified RPC.',
    exclusions: 'Denominator must be dialled leads, not total fetched leads. Zero dialled leads returns null.',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff',
    additive: false,
    treatmentOfUnknown: 'explicit_false_only',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'calls'],
    caveats: ['Denominator must be dialled leads, not total fetched leads.'],
  },

  sale_leads: {
    id: 'sale_leads',
    businessLabel: 'Recorded sales',
    technicalLabel: 'Sale leads',
    plainDefinition: 'Distinct leads with a valid sale timestamp in the selected source. CX3 does not infer billing, collection, underwriting or commercial completion from this field.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['lead_id', 'hlc.sale'],
    precedence: 'Earliest recorded sale timestamp MIN(sale)',
    relationshipKey: 'lead_id',
    unit: 'records',
    numerator: 'COUNT(DISTINCT IF(is_sale, lead_id, NULL))',
    numeratorDescription: 'Distinct leads with recorded sale event.',
    denominator: null,
    denominatorDescription: null,
    eligibility: 'Leads with recorded positive sale timestamp.',
    exclusions: 'Missing, malformed and sentinel sale timestamps. Positive RPC is not required; sale chronology is assessed separately for funnel transitions.',
    scaling: 'none',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Latest verified sale event',
    additive: true,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'admin',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'sales'],
    caveats: ['Recorded sale is independent source evidence, not billing approval or business certification. Sale before capture remains recorded but cannot establish chronological progression.'],
  },

  sales_per_fetched_rate: {
    id: 'sales_per_fetched_rate',
    businessLabel: 'Sales / fetched',
    technicalLabel: 'Lead conversion rate (Sales / fetched)',
    plainDefinition: 'End-to-end conversion rate: percentage of total fetched cohort leads resulting in a recorded sale.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['lead_id', 'hlc.sale'],
    precedence: 'Recorded sales divided by total fetched cohort leads',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'sale_leads',
    numeratorDescription: 'Recorded sale leads',
    denominator: 'fetched_leads',
    denominatorDescription: 'Total fetched leads',
    eligibility: 'All cohort leads.',
    exclusions: 'Zero fetched leads returns null (unavailable).',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff',
    additive: false,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'sales'],
    caveats: ['True lead-to-sale rate; distinct from Sales / RPC.'],
  },

  sales_per_rpc_rate: {
    id: 'sales_per_rpc_rate',
    businessLabel: 'Sales / RPC',
    technicalLabel: 'Independent recorded sales / qualified RPC ratio',
    plainDefinition: 'Independent recorded-sale population divided by qualified RPC population. This is not linked contact-to-sale conversion; the funnel uses the chronological intersection.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['hlc.rpc', 'hlc.sale'],
    precedence: 'Recorded sales divided by verified RPC leads',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'sale_leads',
    numeratorDescription: 'Recorded sale leads',
    denominator: 'rpc_leads',
    denominatorDescription: 'Right-party contacts',
    eligibility: 'Independent recorded sales and qualified RPC populations in the same capture cohort.',
    exclusions: 'Zero RPC leads returns null (unavailable). Do not confuse with overall lead-to-sale rate.',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff',
    additive: false,
    treatmentOfUnknown: 'explicit_false_only',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'calls', 'sales'],
    caveats: ['Do NOT label Sales / RPC as lead-to-sale or linked contact conversion. Independent recorded populations can produce a ratio above 100%.'],
  },

  activated_leads: {
    id: 'activated_leads',
    businessLabel: 'Recorded activations',
    technicalLabel: 'Activated leads',
    plainDefinition: 'Distinct leads with a valid activation timestamp in the selected source. This does not establish billing, collection, contract fulfilment or recurring service status.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['lead_id', 'hlc.activated'],
    precedence: 'Earliest activation timestamp MIN(activated)',
    relationshipKey: 'lead_id',
    unit: 'records',
    numerator: 'COUNT(DISTINCT IF(is_activated, lead_id, NULL))',
    numeratorDescription: 'Distinct leads with a source-recorded activation timestamp.',
    denominator: null,
    denominatorDescription: null,
    eligibility: 'Leads with dated activation event.',
    exclusions: 'Source creation date is not service activation; pending activations excluded.',
    scaling: 'none',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Maturation horizon',
    additive: true,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'admin',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'activations'],
    caveats: ['Activation remains independently recorded even without sale or with invalid chronology. Sale-to-activation conversion uses the ordered intersection.'],
  },

  activation_rate: {
    id: 'activation_rate',
    businessLabel: 'Activations / recorded sales',
    technicalLabel: 'Independent recorded activations / recorded sales ratio',
    plainDefinition: 'Independent recorded-activation population divided by recorded-sale population. This ratio is not linked sale-to-activation conversion; the funnel uses activation at or after a sale that is at or after capture.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['hlc.sale', 'hlc.activated'],
    precedence: 'Activated leads divided by recorded sales',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'activated_leads',
    numeratorDescription: 'Activated leads',
    denominator: 'sale_leads',
    denominatorDescription: 'Sale leads',
    eligibility: 'Independent recorded sales and recorded activations in the same capture cohort.',
    exclusions: 'Zero sales returns null (unavailable). Requires sufficient observation horizon to mature.',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff (e.g. 14–30 days)',
    additive: false,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor', 'source', 'grade'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'sales', 'activations'],
    caveats: ['Independent recorded populations may not be nested and can produce a ratio above 100%. Chronological funnel conversion requires an ordered sale-to-activation intersection.'],
  },

  one_call_dialled_share: {
    id: 'one_call_dialled_share',
    businessLabel: 'One-call dialled share',
    technicalLabel: 'Share of timestamp-confirmed dialled leads with 1 call',
    plainDefinition: 'Percentage of dialled leads that received exactly one recorded call attempt.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['fetched', 'hlc.delivered', 'hlc.first_call_date', 'hlc.total_calls'],
    precedence: 'Count of dialled leads with MAX(total_calls) = 1 divided by dialled leads',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'COUNTIF(is_dialled AND recorded_call_count = 1)',
    numeratorDescription: 'Dialled leads with exactly one recorded cumulative call.',
    denominator: 'dialled_leads',
    denominatorDescription: 'Timestamp-confirmed dialled leads',
    eligibility: 'Timestamp-confirmed dialled leads.',
    exclusions: 'Undialled leads are excluded from both numerator and denominator.',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff',
    additive: false,
    treatmentOfUnknown: 'preserved_in_missing_discrepancy',
    supportedClients: ['*'],
    supportedDimensions: ['vendor'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'calls'],
    caveats: [
      'Both numerator and denominator strictly use the dialled population.',
      'Cannot exceed 100%. Discrepancies between counter=1 and unrecorded timestamps are isolated.',
    ],
  },

  sla_15m_rate: {
    id: 'sla_15m_rate',
    businessLabel: '15-minute first dial SLA',
    technicalLabel: 'SLA compliance (Delivery → dial <= 15m)',
    plainDefinition: 'Percentage of confirmed delivered leads that received a first dial attempt within 15 minutes of delivery.',
    version: METRIC_REGISTRY_VERSION,
    countingGrain: 'lead',
    distinctIdentity: 'lead',
    source: 'leads.hlc_details',
    fields: ['fetched', 'hlc.delivered', 'hlc.first_call_date'],
    precedence: 'Delivered leads called within 900 seconds divided by delivered leads',
    relationshipKey: 'lead_id',
    unit: 'percent',
    numerator: 'COUNTIF(is_delivered AND is_dialled AND delivery_to_dial_sec BETWEEN 0 AND 900)',
    numeratorDescription: 'Delivered leads with first recorded dial within 15 minutes.',
    denominator: 'delivered_leads',
    denominatorDescription: 'Delivered leads',
    eligibility: 'Delivered leads with valid chronological timestamps.',
    exclusions: 'Out-of-order timestamps (dial before delivery) are excluded from latency compliance.',
    scaling: 'percentage_value',
    dateBasis: 'intake_cohort',
    timezone: 'Workspace tenant timezone (Africa/Johannesburg fallback)',
    observationCutoff: 'Cohort maturity cutoff',
    additive: false,
    treatmentOfUnknown: 'zero_not_assumed',
    supportedClients: ['*'],
    supportedDimensions: ['vendor'],
    supportedComparisons: ['previous_matched_period'],
    detailPermissions: 'viewer',
    mappingStatus: 'APPROVED',
    sourceContractStatus: 'BUSINESS_MEANING_NOT_VERIFIED',
    reconciliationStatus: 'NOT_VERIFIED',
    dependencies: ['leads', 'deliveries', 'calls'],
    caveats: ['Excludes invalid ordered timestamps from latency calculation.'],
  },
};

/**
 * Format helper honoring exact decimals and currency representations.
 */
export function formatMetricLabel(metricId: string): string {
  return AUTHORITATIVE_METRICS[metricId]?.businessLabel || metricId;
}
