// Detect changes to model/metric implementations before they can reuse a published release identity.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const roots=['contracts/reporting.ts','contracts/naming.ts','server/reporting/query.ts','server/reporting/checks.ts','server/reporting/scope.ts','warehouse/definitions','warehouse/includes'];
const paths=[];function collect(p){if(fs.statSync(p).isDirectory())for(const name of fs.readdirSync(p).sort())collect(path.join(p,name));else paths.push(p.replaceAll('\\','/'));}roots.forEach(collect);
const hash=crypto.createHash('sha256');for(const p of paths.sort())hash.update(p+'\0').update(fs.readFileSync(p)).update('\0');
const text=`// Generated by scripts/engine-stamp.cjs; includes metric, query and warehouse source hashes.\nexport const ENGINE_HASH = '${hash.digest('hex')}';\n`;
const target='server/reporting/buildStamp.ts';
if(process.argv.includes('--check')){if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==text)throw new Error('Reporting engine changed. Regenerate and commit buildStamp.ts; old releases must not silently reuse changed logic.');console.log('Reporting engine fingerprint matches tracked source.');}
else fs.writeFileSync(target,text);
