import fs from 'node:fs';

const read = (path: string) => fs.readFileSync(path, 'utf8');

const appSource = fs.existsSync('src/app/AppRouter.tsx') ? read('src/app/AppRouter.tsx') : read('src/App.tsx');
const apiSource = read('server/api.ts');
const vettingSource = read('server/vetting/router.ts');
const sourceRouterSource = read('server/bigquery/sourceRouter.ts');
const reportingSource = read('server/reporting/router.ts');
const blcSource = read('server/blc/router.ts');
const savedAnalysisSource = read('server/savedAnalyses/router.ts');

function routeTarget(element: string) {
  const nav = element.match(/<(?:Navigate|ScopePreservingRedirect)\s+to="([^"]+)"/);
  if (nav) return `redirect → ${nav[1]}`;
  if (/cx-route-error/.test(element)) return 'inline 404';
  const component = element.match(/<([A-Z][A-Za-z0-9_]*)\b/);
  if (component) return component[1];
  return element.replace(/\s+/g, ' ').trim().slice(0, 80);
}

function extractUiRoutes(source: string) {
  return source.split('\n').flatMap(line => {
    const match = line.match(/<Route\s+path="([^"]+)"\s+element=\{(.+)\}\s*\/>/);
    return match ? [{ path: match[1], target: routeTarget(match[2]) }] : [];
  });
}

function directRoutes(source: string, routerName: string, prefix: string, sourceLabel: string) {
  const out: Array<{ method: string; path: string; source: string }> = [];
  const expression = new RegExp(`${routerName}\\.(get|post|put|patch|delete)\\(\\s*['\"]([^'\"]+)['\"]`, 'g');
  for (const match of source.matchAll(expression)) {
    out.push({ method: match[1].toUpperCase(), path: `${prefix}${match[2]}`, source: sourceLabel });
  }
  return out;
}

function buildApiRoutes() {
  const routes = [
    { method: 'GET', path: '/api/health', source: 'server.ts' },
    ...directRoutes(apiSource, 'analyticsRouter', '/api/analytics', 'server/api.ts'),
    ...directRoutes(vettingSource, 'router', '/api/analytics', 'server/vetting/router.ts'),
    ...directRoutes(sourceRouterSource, 'router', '/api/analytics', 'server/bigquery/sourceRouter.ts'),
    ...directRoutes(reportingSource, 'router', '/api/reporting', 'server/reporting/router.ts'),
    ...directRoutes(blcSource, 'router', '/api/analytics', 'server/blc/router.ts'),
    ...directRoutes(savedAnalysisSource, 'router', '/api/saved-analyses', 'server/savedAnalyses/router.ts'),
  ];

  const reportsBlock = apiSource.match(/const reports:[\s\S]*?=\s*\[([\s\S]*?)\n\];/);
  if (reportsBlock) {
    for (const group of reportsBlock[1].matchAll(/\[\[([^\]]+)\],/g)) {
      for (const route of group[1].matchAll(/['"]([^'"]+)['"]/g)) {
        routes.push({ method: 'GET', path: `/api/analytics/${route[1]}`, source: 'server/api.ts reports registry' });
      }
    }
  }

  const dynamicLoop = apiSource.match(/for \(const route of \[([^\]]+)\]\)/);
  if (dynamicLoop) {
    for (const route of dynamicLoop[1].matchAll(/['"]([^'"]+)['"]/g)) {
      routes.push({ method: 'GET', path: `/api/analytics${route[1]}`, source: 'server/api.ts dynamic analytics' });
      routes.push({ method: 'POST', path: `/api/analytics${route[1]}`, source: 'server/api.ts dynamic analytics' });
    }
  }

  const seen = new Set<string>();
  return routes
    .filter(route => {
      const key = `${route.method} ${route.path}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

const escapeCell = (value: string) => String(value).replace(/\|/g, '\\|');

function generateInventory() {
  const ui = extractUiRoutes(appSource);
  const api = buildApiRoutes();
  return [
    '# Generated surface inventory',
    '',
    '> Generated from the current source tree by `npm run docs:surfaces`. Do not edit this file manually.',
    '',
    '## UI routes',
    '',
    '| Route | Current target |',
    '| --- | --- |',
    ...ui.map(route => `| \`${escapeCell(route.path)}\` | ${escapeCell(route.target)} |`),
    '',
    '## API routes',
    '',
    '| Method | Path | Declared in |',
    '| --- | --- | --- |',
    ...api.map(route => `| ${route.method} | \`${escapeCell(route.path)}\` | \`${escapeCell(route.source)}\` |`),
    '',
    '## API boundary',
    '',
    '- `/api/analytics/*` is authenticated, tenant-scoped operational analytics and is stamped `UNVERIFIED`.',
    '- `/api/reporting/*` is the separate versioned evidence-reporting path.',
    '- `/api/saved-analyses/*` stores personal, authenticated owner/workspace-scoped investigation definitions; no analytical records or results are persisted.',
    '- `/api/bq/*` is retired and returns HTTP 410.',
    '- `/api/health` is liveness only and is the sole unauthenticated API route.',
    '',
  ].join('\n');
}

const outputPath = 'docs/SURFACE-INVENTORY.md';
const expected = generateInventory();
const check = process.argv.includes('--check');

if (check) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
  if (current !== expected) {
    console.error(`${outputPath} is stale. Run npm run docs:surfaces and commit the result.`);
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(outputPath, expected);
  console.log(`Updated ${outputPath}`);
}
